"""baseline v1.37.43 schema

Revision ID: 18a3b4fd6e33
Revises: 
Create Date: 2026-06-09 22:51:10.681715
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '18a3b4fd6e33'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('token_epoch', sa.Integer(), server_default='0', nullable=False),
    sa.Column('totp_secret_enc', sa.String(length=255), nullable=True),
    sa.Column('totp_pending_secret_enc', sa.String(length=255), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_users_username'), ['username'], unique=True)

    op.create_table('bot_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_kicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bot_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bot_users_telegram_id'), ['telegram_id'], unique=True)

    op.create_table('financial_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('panel_key', sa.String(length=128), nullable=False),
    sa.Column('reseller_name', sa.String(length=255), nullable=False),
    sa.Column('reseller_admin_uuid', sa.String(length=64), nullable=False),
    sa.Column('period_label', sa.String(length=32), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('usage_gb', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('price_per_gb', sa.Integer(), nullable=False),
    sa.Column('amount_toman', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_usdt', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('txid', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_records_invoice_id'), ['invoice_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_financial_records_panel_key'), ['panel_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_records_period_label'), ['period_label'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_records_reseller_admin_uuid'), ['reseller_admin_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_records_reseller_name'), ['reseller_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_records_status'), ['status'], unique=False)

    op.create_table('panels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('proxy_path_enc', sa.String(length=512), nullable=False),
    sa.Column('owner_uuid', sa.String(length=64), nullable=False),
    sa.Column('admin_api_key_enc', sa.String(length=512), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('unknown', 'ok', 'error', 'disabled', name='panelstatus', native_enum=False, length=16), nullable=False),
    sa.Column('source', sa.Enum('backup_json', 'admin_api', 'sample', name='syncsource', native_enum=False, length=16), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('panels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_panels_key'), ['key'], unique=True)

    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('usage_meters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('panel_id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.String(length=64), nullable=False),
    sa.Column('period_label', sa.String(length=32), nullable=False),
    sa.Column('added_by_uuid', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quota_added_gb', sa.Numeric(precision=16, scale=3), nullable=False),
    sa.Column('consumed_gb', sa.Numeric(precision=16, scale=3), nullable=False),
    sa.Column('overage_gb', sa.Numeric(precision=16, scale=3), nullable=False),
    sa.Column('edit_renewal_gb', sa.Numeric(precision=16, scale=3), nullable=False),
    sa.Column('reset_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('panel_id', 'user_uuid', 'period_label', name='uq_usage_meter')
    )
    with op.batch_alter_table('usage_meters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_meters_added_by_uuid'), ['added_by_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_meters_panel_id'), ['panel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_meters_period_label'), ['period_label'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_meters_user_uuid'), ['user_uuid'], unique=False)

    op.create_table('end_user_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('panel_id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('added_by_uuid', sa.String(length=64), nullable=True),
    sa.Column('usage_limit_gb', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('current_usage_gb', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('package_days', sa.Integer(), nullable=True),
    sa.Column('enable', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=True),
    sa.Column('last_online', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meter_provisioned_gb', sa.Numeric(precision=16, scale=3), nullable=False),
    sa.Column('meter_consumed_gb', sa.Numeric(precision=16, scale=3), nullable=False),
    sa.Column('meter_init', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('panel_id', 'user_uuid', name='uq_enduser_panel_uuid')
    )
    with op.batch_alter_table('end_user_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_end_user_snapshots_added_by_uuid'), ['added_by_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_end_user_snapshots_panel_id'), ['panel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_end_user_snapshots_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_end_user_snapshots_user_uuid'), ['user_uuid'], unique=False)

    op.create_table('resellers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('panel_id', sa.Integer(), nullable=False),
    sa.Column('admin_uuid', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_admin_uuid', sa.String(length=64), nullable=True),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('panel_telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('bot_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('link_tag', sa.String(length=255), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price_per_gb', sa.Integer(), nullable=True),
    sa.Column('min_sale_toman', sa.Integer(), nullable=True),
    sa.Column('exclude_from_billing', sa.Boolean(), nullable=False),
    sa.Column('panel_max_users', sa.Integer(), nullable=True),
    sa.Column('panel_max_active_users', sa.Integer(), nullable=True),
    sa.Column('can_add_admin', sa.Boolean(), nullable=False),
    sa.Column('gb_cap', sa.Integer(), nullable=True),
    sa.Column('gb_cap_alerted_period', sa.String(length=7), nullable=True),
    sa.Column('enforcement_state', sa.Enum('active', 'warned', 'enforced', name='enforcementstate', native_enum=False, length=16), nullable=False),
    sa.Column('max_users_snapshot', sa.Integer(), nullable=True),
    sa.Column('max_active_users_snapshot', sa.Integer(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('panel_id', 'admin_uuid', name='uq_reseller_panel_uuid')
    )
    with op.batch_alter_table('resellers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resellers_admin_uuid'), ['admin_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_resellers_bot_chat_id'), ['bot_chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resellers_panel_id'), ['panel_id'], unique=False)

    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('panel_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('backup_json', 'admin_api', 'sample', name='syncsource', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('running', 'success', 'failed', name='syncstatus', native_enum=False, length=16), nullable=False),
    sa.Column('admin_count', sa.Integer(), nullable=False),
    sa.Column('user_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_runs_panel_id'), ['panel_id'], unique=False)

    op.create_table('webauthn_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.String(length=512), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webauthn_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webauthn_credentials_credential_id'), ['credential_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_webauthn_credentials_user_id'), ['user_id'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reseller_id', sa.Integer(), nullable=False),
    sa.Column('panel_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('period_label', sa.String(length=32), nullable=False),
    sa.Column('usage_gb', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('users_count', sa.Integer(), nullable=False),
    sa.Column('price_per_gb', sa.Integer(), nullable=False),
    sa.Column('amount_toman', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('base_amount_toman', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('min_sale_toman', sa.Integer(), nullable=False),
    sa.Column('floor_applied', sa.Boolean(), nullable=False),
    sa.Column('usdt_rate', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount_usdt', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'paid', 'overdue', 'enforced', 'canceled', name='invoicestatus', native_enum=False, length=16), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deferred_until', sa.Date(), nullable=True),
    sa.Column('defer_note', sa.String(length=255), nullable=True),
    sa.Column('pdf_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ),
    sa.ForeignKeyConstraint(['reseller_id'], ['resellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reseller_id', 'period_start', 'period_end', name='uq_invoice_period')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_panel_id'), ['panel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_reseller_id'), ['reseller_id'], unique=False)

    op.create_table('delivery_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reseller_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('invoice', 'reminder1', 'reminder2', 'warning', 'payment_ack', 'abuse_notice', 'generic', name='deliverykind', native_enum=False, length=16), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('sent', 'failed', 'blocked', 'unmatched', 'skipped', name='deliverystatus', native_enum=False, length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('message_preview', sa.Text(), nullable=True),
    sa.Column('tg_message_id', sa.BigInteger(), nullable=True),
    sa.Column('tg_message_ids', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reseller_id'], ['resellers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_log_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_log_reseller_id'), ['reseller_id'], unique=False)

    op.create_table('enforcement_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reseller_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('warn', 'disable_users', 'zero_limits', 'restore', name='enforcementactiontype', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('planned', 'dry_run', 'done', 'failed', 'reverted', name='enforcementactionstatus', native_enum=False, length=16), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('affected_count', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reseller_id'], ['resellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enforcement_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enforcement_actions_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enforcement_actions_reseller_id'), ['reseller_id'], unique=False)

    op.create_table('invoice_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('end_user_uuid', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('usage_gb', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('added_by_uuid', sa.String(length=64), nullable=True),
    sa.Column('sub_reseller_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_lines_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reseller_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.Enum('usdt_txid', 'usdt_hd', 'manual', 'screenshot', 'ton_txid', name='paymentmethod', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'rejected', 'duplicate', name='paymentstatus', native_enum=False, length=16), nullable=False),
    sa.Column('chain', sa.String(length=16), nullable=False),
    sa.Column('txid', sa.String(length=80), nullable=True),
    sa.Column('from_address', sa.String(length=64), nullable=True),
    sa.Column('to_address', sa.String(length=64), nullable=True),
    sa.Column('confirmations', sa.Integer(), nullable=False),
    sa.Column('amount_usdt', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('amount_toman', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('proof_path', sa.String(length=255), nullable=True),
    sa.Column('settled_invoice_ids', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reseller_id'], ['resellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_reseller_id'), ['reseller_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_txid'), ['txid'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_txid'))
        batch_op.drop_index(batch_op.f('ix_payments_reseller_id'))
        batch_op.drop_index(batch_op.f('ix_payments_invoice_id'))

    op.drop_table('payments')
    with op.batch_alter_table('invoice_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_lines_invoice_id'))

    op.drop_table('invoice_lines')
    with op.batch_alter_table('enforcement_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enforcement_actions_reseller_id'))
        batch_op.drop_index(batch_op.f('ix_enforcement_actions_invoice_id'))

    op.drop_table('enforcement_actions')
    with op.batch_alter_table('delivery_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_log_reseller_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_log_invoice_id'))

    op.drop_table('delivery_log')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_reseller_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_panel_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('webauthn_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webauthn_credentials_user_id'))
        batch_op.drop_index(batch_op.f('ix_webauthn_credentials_credential_id'))

    op.drop_table('webauthn_credentials')
    with op.batch_alter_table('sync_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_runs_panel_id'))

    op.drop_table('sync_runs')
    with op.batch_alter_table('resellers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resellers_panel_id'))
        batch_op.drop_index(batch_op.f('ix_resellers_bot_chat_id'))
        batch_op.drop_index(batch_op.f('ix_resellers_admin_uuid'))

    op.drop_table('resellers')
    with op.batch_alter_table('end_user_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_end_user_snapshots_user_uuid'))
        batch_op.drop_index(batch_op.f('ix_end_user_snapshots_start_date'))
        batch_op.drop_index(batch_op.f('ix_end_user_snapshots_panel_id'))
        batch_op.drop_index(batch_op.f('ix_end_user_snapshots_added_by_uuid'))

    op.drop_table('end_user_snapshots')
    with op.batch_alter_table('usage_meters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_meters_user_uuid'))
        batch_op.drop_index(batch_op.f('ix_usage_meters_period_label'))
        batch_op.drop_index(batch_op.f('ix_usage_meters_panel_id'))
        batch_op.drop_index(batch_op.f('ix_usage_meters_added_by_uuid'))

    op.drop_table('usage_meters')
    op.drop_table('settings')
    with op.batch_alter_table('panels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_panels_key'))

    op.drop_table('panels')
    with op.batch_alter_table('financial_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_records_status'))
        batch_op.drop_index(batch_op.f('ix_financial_records_reseller_name'))
        batch_op.drop_index(batch_op.f('ix_financial_records_reseller_admin_uuid'))
        batch_op.drop_index(batch_op.f('ix_financial_records_period_label'))
        batch_op.drop_index(batch_op.f('ix_financial_records_panel_key'))
        batch_op.drop_index(batch_op.f('ix_financial_records_invoice_id'))

    op.drop_table('financial_records')
    with op.batch_alter_table('bot_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_users_telegram_id'))

    op.drop_table('bot_users')
    with op.batch_alter_table('app_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_users_username'))

    op.drop_table('app_users')
    # ### end Alembic commands ###
