"""add storefront tables

Revision ID: 557ce30f0d9c
Revises: c8d2f1a4e6b9
Create Date: 2026-06-26 23:53:38.369804
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "557ce30f0d9c"
down_revision: str | None = "c8d2f1a4e6b9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storefront_bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reseller_id', sa.Integer(), nullable=False),
    sa.Column('panel_id', sa.Integer(), nullable=False),
    sa.Column('bot_token_enc', sa.String(length=512), nullable=False),
    sa.Column('bot_username', sa.String(length=64), nullable=True),
    sa.Column('bot_telegram_id', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_error', sa.String(length=300), nullable=True),
    sa.Column('support_contact', sa.String(length=128), nullable=True),
    sa.Column('welcome_text', sa.Text(), nullable=True),
    sa.Column('pay_card_enabled', sa.Boolean(), nullable=False),
    sa.Column('pay_usdt_enabled', sa.Boolean(), nullable=False),
    sa.Column('pay_ton_enabled', sa.Boolean(), nullable=False),
    sa.Column('card_number', sa.String(length=32), nullable=True),
    sa.Column('card_holder', sa.String(length=128), nullable=True),
    sa.Column('usdt_address', sa.String(length=128), nullable=True),
    sa.Column('ton_address', sa.String(length=128), nullable=True),
    sa.Column('channel_id', sa.String(length=64), nullable=True),
    sa.Column('channel_link', sa.String(length=255), nullable=True),
    sa.Column('channel_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reseller_id'], ['resellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reseller_id', name='uq_storefront_bot_reseller')
    )
    with op.batch_alter_table('storefront_bots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_storefront_bots_bot_telegram_id'), ['bot_telegram_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_storefront_bots_panel_id'), ['panel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_storefront_bots_reseller_id'), ['reseller_id'], unique=False)

    op.create_table('storefront_customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storefront_bot_id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('wallet_balance_toman', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('banned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('wallet_balance_toman >= 0', name='ck_storefront_wallet_nonneg'),
    sa.ForeignKeyConstraint(['storefront_bot_id'], ['storefront_bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storefront_bot_id', 'telegram_id', name='uq_storefront_customer')
    )
    with op.batch_alter_table('storefront_customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_storefront_customers_storefront_bot_id'), ['storefront_bot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_storefront_customers_telegram_id'), ['telegram_id'], unique=False)

    op.create_table('storefront_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storefront_bot_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('gb', sa.Integer(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('price_toman', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('days >= 0', name='ck_storefront_plan_days_nonneg'),
    sa.CheckConstraint('gb >= 0', name='ck_storefront_plan_gb_nonneg'),
    sa.CheckConstraint('price_toman >= 0', name='ck_storefront_plan_price_nonneg'),
    sa.ForeignKeyConstraint(['storefront_bot_id'], ['storefront_bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('storefront_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_storefront_plans_storefront_bot_id'), ['storefront_bot_id'], unique=False)

    op.create_table('storefront_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('gb', sa.Integer(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('price_toman', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('panel_user_uuid', sa.String(length=64), nullable=True),
    sa.Column('sub_link', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['storefront_customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['storefront_plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('storefront_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_storefront_orders_customer_id'), ['customer_id'], unique=False)

    op.create_table('storefront_wallet_txns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('amount_toman', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=True),
    sa.Column('proof_path', sa.String(length=255), nullable=True),
    sa.Column('txid', sa.String(length=120), nullable=True),
    sa.Column('chain', sa.String(length=16), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['storefront_customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('storefront_wallet_txns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_storefront_wallet_txns_customer_id'), ['customer_id'], unique=False)

    with op.batch_alter_table('resellers', schema=None) as batch_op:
        # server_default backfills existing reseller rows; the model has only a Python default, and
        # alembic check does not compare server defaults, so leaving it here causes no drift.
        # Use sa.false() (NOT text("0")) — it renders a real BOOLEAN literal on Postgres (`false`)
        # while still compiling to 0 on SQLite. A raw "0" is rejected by Postgres for a BOOLEAN column.
        batch_op.add_column(sa.Column(
            "storefront_enabled", sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column("storefront_monthly_fee_toman", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resellers', schema=None) as batch_op:
        batch_op.drop_column('storefront_monthly_fee_toman')
        batch_op.drop_column('storefront_enabled')

    with op.batch_alter_table('storefront_wallet_txns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storefront_wallet_txns_customer_id'))

    op.drop_table('storefront_wallet_txns')
    with op.batch_alter_table('storefront_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storefront_orders_customer_id'))

    op.drop_table('storefront_orders')
    with op.batch_alter_table('storefront_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storefront_plans_storefront_bot_id'))

    op.drop_table('storefront_plans')
    with op.batch_alter_table('storefront_customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storefront_customers_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_storefront_customers_storefront_bot_id'))

    op.drop_table('storefront_customers')
    with op.batch_alter_table('storefront_bots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storefront_bots_reseller_id'))
        batch_op.drop_index(batch_op.f('ix_storefront_bots_panel_id'))
        batch_op.drop_index(batch_op.f('ix_storefront_bots_bot_telegram_id'))

    op.drop_table('storefront_bots')
    # ### end Alembic commands ###
