"""storefront operations + provisioning lease (security round-2 F4/F11/F5)

Revision ID: 7968884fecbd
Revises: f5b8d1a3c6e9
Create Date: 2026-07-15

Security remediation Round 2, Batch B (docs/SECURITY_REVIEW_PLAN2.md):
- F4: a durable `storefront_operations` table keyed by a unique `op_id` (minted before the confirm
  button) → purchase/renewal replays are exactly-once (cached terminal result, no second debit).
- F11: the debit links to its operation (`storefront_wallet_txns.operation_id`) and a partial-unique
  index `uq_sfwallet_reversal_per_operation` (WHERE kind='renew_reversal') guarantees a crashed
  renewal is reversed exactly once by whichever of the inline handler / reconciler gets there first.
- F5: `storefront_orders.lease_expires_at` is a durable provisioning LEASE the reaper honors, so it
  never refunds an in-flight provision.

New table + two nullable columns; no data transform (existing in-flight orders have NULL lease → the
reconciler's legacy branches handle them). Runs on SQLite too (partial index carries sqlite_where +
postgresql_where); `by_admin` uses sa.false() so the DEFAULT is portable to Postgres.
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '7968884fecbd'
down_revision: str | None = 'f5b8d1a3c6e9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storefront_operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('op_id', sa.String(length=64), nullable=False),
    sa.Column('op_type', sa.String(length=16), nullable=False),
    sa.Column('storefront_bot_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('prior_status', sa.String(length=16), nullable=True),
    sa.Column('price_toman', sa.Integer(), nullable=False),
    sa.Column('gb', sa.Integer(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('by_admin', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('debit_txn_id', sa.Integer(), nullable=True),
    sa.Column('result_order_id', sa.Integer(), nullable=True),
    sa.Column('result_sub_link', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('storefront_operations', schema=None) as batch_op:
        batch_op.create_index('ix_storefront_operation_status_order', ['status', 'order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_storefront_operations_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_storefront_operations_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_storefront_operations_storefront_bot_id'), ['storefront_bot_id'], unique=False)
        batch_op.create_index('uq_storefront_operation_op_id', ['op_id'], unique=True)

    with op.batch_alter_table('storefront_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('storefront_wallet_txns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operation_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_storefront_wallet_txns_operation_id'), ['operation_id'], unique=False)
        batch_op.create_index('uq_sfwallet_reversal_per_operation', ['operation_id'], unique=True, sqlite_where=sa.text("kind = 'renew_reversal'"), postgresql_where=sa.text("kind = 'renew_reversal'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storefront_wallet_txns', schema=None) as batch_op:
        batch_op.drop_index('uq_sfwallet_reversal_per_operation', sqlite_where=sa.text("kind = 'renew_reversal'"), postgresql_where=sa.text("kind = 'renew_reversal'"))
        batch_op.drop_index(batch_op.f('ix_storefront_wallet_txns_operation_id'))
        batch_op.drop_column('operation_id')

    with op.batch_alter_table('storefront_orders', schema=None) as batch_op:
        batch_op.drop_column('lease_expires_at')

    with op.batch_alter_table('storefront_operations', schema=None) as batch_op:
        batch_op.drop_index('uq_storefront_operation_op_id')
        batch_op.drop_index(batch_op.f('ix_storefront_operations_storefront_bot_id'))
        batch_op.drop_index(batch_op.f('ix_storefront_operations_order_id'))
        batch_op.drop_index(batch_op.f('ix_storefront_operations_customer_id'))
        batch_op.drop_index('ix_storefront_operation_status_order')

    op.drop_table('storefront_operations')
    # ### end Alembic commands ###
